"""The generation planner: engine and settings resolved BEFORE the cache key.

Two failures this exists to prevent. A stem generated by one model under a filename and
ledger entry that name another - which is what a swap inside the worker would do. And a
control that changes the audio without changing the key: engine defaults used to enter the
key only when a cue set them, so changing a default silently reused every stem and the user
heard nothing change.
"""

from __future__ import annotations

import pytest

from hudka import engines, render
from hudka.engines import hardware
from hudka.engines.base import GenerateRequest
from hudka.engines.hardware import Hardware, Tier


def hw(**kw) -> Hardware:
    base = dict(device="cuda", gpu_name="RTX 4070", total_vram_gb=12.9, free_vram_gb=9.0,
                bf16=True, ram_gb=64.0, cores=24)
    base.update(kw)
    return Hardware(**base)


CPU = hw(device="cpu")
LITE = hw(free_vram_gb=5.0)
MEDIUM = hw(free_vram_gb=9.0)


def plan(engine, kind, duration=30.0, *, steps=None, cfg=None, neg="", quality="auto", machine=MEDIUM, notes=None):
    return render.plan_generation(engine, kind, duration, steps=steps, cfg_scale=cfg,
                                  negative_prompt=neg, quality=quality, hw=machine, notes=notes,
                                  cue_id="bed")


class TestResolvedStepsEnterTheKey:
    def test_cpu_and_gpu_resolve_different_steps_and_therefore_different_keys(self):
        on_cpu = plan("stable-audio-3-small-music", "music", machine=CPU)
        on_gpu = plan("stable-audio-3-small-music", "music", machine=LITE)
        assert on_cpu.extra == {"steps": 8}
        assert on_gpu.extra == {"steps": 50}
        key = lambda p: GenerateRequest("x", 30.0, 1, extra=p.extra).cache_key(p.engine)
        assert key(on_cpu) != key(on_gpu), "different audio must never share a file"

    def test_an_explicit_setting_wins_everywhere(self):
        for machine in (CPU, LITE, MEDIUM):
            assert plan("stable-audio-3-small-music", "music", steps=12, machine=machine).extra["steps"] == 12

    def test_one_shots_keep_eight_steps_on_every_tier(self):
        for machine in (CPU, LITE, MEDIUM):
            assert plan("stable-audio-3-small-sfx", "sfx", machine=machine).extra == {"steps": 8}

    def test_ambience_gets_bed_steps_on_a_gpu(self):
        assert plan("stable-audio-3-small-sfx", "ambience", machine=LITE).extra["steps"] == 50
        assert plan("stable-audio-3-small-sfx", "ambience", machine=CPU).extra["steps"] == 8

    def test_the_stub_gets_no_steps_so_every_existing_test_key_is_unchanged(self):
        assert plan("silence", "music", machine=LITE).extra == {}
        assert plan("silence", "sfx", steps=25, machine=LITE).extra == {"steps": 25}

    def test_other_generation_controls_still_pass_through(self):
        p = plan("stable-audio-3-small-sfx", "sfx", cfg=3.0, neg="reverb", machine=CPU)
        assert p.extra == {"steps": 8, "cfg_scale": 3.0, "negative_prompt": "reverb"}


class TestFallbackIsPlannedNotSmuggled:
    def test_medium_on_a_busy_card_becomes_small_with_a_note(self):
        notes = []
        p = plan("stable-audio-3-medium", "music", 60.0, machine=hw(free_vram_gb=3.0), notes=notes)
        assert p.engine == "stable-audio-3-small-music"
        assert len(notes) == 1
        assert "needs about" in notes[0] and "3.0 GB is free" in notes[0] and "bed" in notes[0]
        assert "other applications hold 9.9 GB" in notes[0]

    def test_medium_that_fits_stays_medium_without_a_note(self):
        notes = []
        p = plan("stable-audio-3-medium", "music", 60.0, machine=MEDIUM, notes=notes)
        assert p.engine == "stable-audio-3-medium" and notes == []
        assert p.extra == {"steps": 50}

    def test_once_medium_fits_it_fits_any_length_it_can_generate(self):
        """Measured flat: a 380 s bed peaks where a 30 s one does."""
        assert plan("stable-audio-3-medium", "music", 380.0, machine=MEDIUM).engine == "stable-audio-3-medium"
        assert plan("stable-audio-3-medium", "music", 380.0, machine=hw(free_vram_gb=8.0)).engine \
            == "stable-audio-3-small-music"

    def test_medium_on_cpu_is_left_alone(self):
        """Today's behaviour: it runs, slowly. Not this planner's call to make."""
        assert plan("stable-audio-3-medium", "music", machine=CPU).engine == "stable-audio-3-medium"

    def test_ambience_falls_back_to_its_own_small_model(self):
        p = plan("stable-audio-3-medium", "ambience", 60.0, machine=hw(free_vram_gb=3.0))
        assert p.engine == "stable-audio-3-small-sfx"


class TestQuality:
    def test_fast_flattens_steps_and_skips_the_big_load(self):
        p = plan("stable-audio-3-medium", "music", quality="fast", machine=MEDIUM)
        assert p.engine == "stable-audio-3-small-music" and p.extra == {"steps": 8}
        assert plan("stable-audio-3-small-sfx", "ambience", quality="fast", machine=LITE).extra == {"steps": 8}

    def test_best_puts_one_shots_on_medium_only_when_it_fits(self):
        assert plan("stable-audio-3-small-sfx", "sfx", quality="best", machine=MEDIUM).engine == "stable-audio-3-medium"
        assert plan("stable-audio-3-small-sfx", "sfx", quality="best", machine=LITE).engine == "stable-audio-3-small-sfx"
        assert plan("stable-audio-3-small-sfx", "sfx", quality="best", machine=CPU).engine == "stable-audio-3-small-sfx"

    def test_auto_leaves_one_shots_on_the_purpose_trained_model(self):
        assert plan("stable-audio-3-small-sfx", "sfx", machine=MEDIUM).engine == "stable-audio-3-small-sfx"

    def test_the_sheet_defaults_to_auto_and_round_trips(self):
        from hudka.schema import CueSheet, VideoInfo

        info = VideoInfo(path="x.mp4", duration=10.0, fps=30.0, width=1920, height=1080,
                         has_audio=True, has_dialogue=False)
        sheet = CueSheet(video=info)
        assert sheet.quality == "auto"
        again = CueSheet.model_validate_json(sheet.model_copy(update={"quality": "best"}).model_dump_json())
        assert again.quality == "best"
        with pytest.raises(Exception):
            CueSheet(video=info, quality="ultra")


class TestDescribe:
    def test_stable_audio_reports_device_precision_and_steps(self, monkeypatch):
        from hudka.engines.stable_audio3 import StableAudio3Engine

        monkeypatch.setattr(hardware, "detect", lambda refresh=False: MEDIUM)
        cpu = StableAudio3Engine("stable-audio-3-small-music", device="cpu")
        d = cpu.describe(GenerateRequest("x", 2.0, 1, extra={"steps": 8}))
        assert d["device"] == "cpu" and d["precision"] == "fp32" and d["steps"] == 8
        gpu = StableAudio3Engine("stable-audio-3-medium", device="cuda")
        d = gpu.describe(GenerateRequest("x", 2.0, 1, extra={"steps": 50}))
        assert d["precision"] == "fp16" and d["text_encoder"] == "bf16" and d["variant"] == "medium"

    def test_the_parent_never_needs_torch_to_describe(self, monkeypatch):
        import sys

        from hudka.engines.stable_audio3 import StableAudio3Engine

        monkeypatch.setattr(hardware, "detect", lambda refresh=False: MEDIUM)
        monkeypatch.delenv("HUDKA_ALLOW_TORCH_PROBE", raising=False)
        monkeypatch.setitem(sys.modules, "torch", None)
        engine = StableAudio3Engine("stable-audio-3-small-sfx")       # device unset
        d = engine.describe(GenerateRequest("x", 2.0, 1))
        assert d["device"] == "cuda" and d["steps"] == 8

    def test_the_stub_says_only_what_it_is(self):
        d = engines.build("silence").describe(GenerateRequest("x", 2.0, 1))
        assert d == {"engine": "silence"}


class TestLedgerSettings:
    def test_settings_text(self):
        from hudka.provenance import settings_text

        assert settings_text({"device": "cuda", "precision": "fp16", "steps": 50}) == "cuda · fp16 · 50 steps"
        assert settings_text({"engine": "silence"}) == ""
        assert settings_text({}) == ""

    def test_a_render_records_settings_per_stem(self, tmp_path, fixture_video):
        """Through the real pipeline on the stub: every record carries the settings key and
        the report has the column, so a medium render will read 'cuda · fp16 · 50 steps'."""
        import json

        from hudka import analyze, design
        from hudka.schema import CueSheet

        analyze.analyze(fixture_video, tmp_path / "analysis")        # writes analysis.json
        analysis = json.loads((tmp_path / "analysis" / "analysis.json").read_text(encoding="utf-8"))
        sheet = design.scaffold(analysis, preset="short-form", engine="silence")
        result = render.render(sheet, tmp_path / "out")
        records = json.loads(result.provenance.read_text(encoding="utf-8"))["records"]
        assert records and all("settings" in r for r in records)
        report = (tmp_path / "out" / "LICENSE-REPORT.md").read_text(encoding="utf-8")
        assert "| Settings |" in report
