"""The licence audit trail.

Every generated file records which engine made it, under what licence, from what prompt
and seed. Two artefacts come out of this: provenance.json for machines, and
LICENSE-REPORT.md for humans - the document to point at if a claim is ever raised, or to
hand a client who asks what the audio is cleared for.

The render fails if any stem is missing an entry. An untracked file is exactly the thing
this project exists to avoid.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from .engines.base import Licence


@dataclass
class Record:
    cue_id: str
    kind: str
    file: str
    engine: str
    licence: str
    licence_url: str
    commercial_use: bool
    prompt: str
    seed: int
    duration: float
    revenue_cap_usd: int | None = None
    territory_exclusions: tuple[str, ...] = ()
    training_data: str = ""
    cached: bool = False


@dataclass
class Ledger:
    video: str
    created: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    records: list[Record] = field(default_factory=list)

    def add(self, *, cue_id: str, kind: str, file: Path, engine_id: str, licence: Licence,
            prompt: str, seed: int, duration: float, cached: bool = False) -> None:
        self.records.append(Record(
            cue_id=cue_id, kind=kind, file=Path(file).name, engine=engine_id,
            licence=licence.name, licence_url=licence.url, commercial_use=licence.commercial,
            prompt=prompt, seed=seed, duration=round(duration, 3),
            revenue_cap_usd=licence.revenue_cap_usd,
            territory_exclusions=licence.territory_exclusions,
            training_data=licence.training_data, cached=cached,
        ))

    def engines_used(self) -> dict[str, Record]:
        return {r.engine: r for r in self.records}

    def verify(self, stems_dir: Path) -> None:
        """Fail loudly if any produced stem lacks a provenance entry."""
        tracked = {r.file for r in self.records}
        on_disk = {p.name for p in Path(stems_dir).rglob("*.wav")}
        missing = on_disk - tracked
        if missing:
            raise RuntimeError(
                "these stems have no provenance entry, so their licence is unknown: "
                + ", ".join(sorted(missing))
            )
        blank = [r.file for r in self.records if not r.licence]
        if blank:
            raise RuntimeError("stems with an empty licence field: " + ", ".join(blank))

    def save(self, out_dir: Path) -> tuple[Path, Path]:
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        json_path = out_dir / "provenance.json"
        json_path.write_text(
            json.dumps({
                "video": self.video,
                "created": self.created,
                "records": [asdict(r) for r in self.records],
            }, indent=2) + "\n",
            encoding="utf-8",
        )

        md_path = out_dir / "LICENSE-REPORT.md"
        md_path.write_text(self.to_markdown(), encoding="utf-8")
        return json_path, md_path

    def to_markdown(self) -> str:
        lines = [
            "# Audio licence report",
            "",
            f"**Source video:** `{Path(self.video).name}`  ",
            f"**Generated:** {self.created}  ",
            f"**Assets:** {len(self.records)}",
            "",
            "Every sound in this mix was generated by a model listed below. No third-party "
            "recordings, samples or library tracks were used.",
            "",
            "## Models used",
            "",
        ]

        for engine, rec in sorted(self.engines_used().items()):
            count = sum(1 for r in self.records if r.engine == engine)
            lines.append(f"### {engine}")
            lines.append("")
            lines.append(f"- **Licence:** [{rec.licence}]({rec.licence_url})"
                         if rec.licence_url else f"- **Licence:** {rec.licence}")
            lines.append(f"- **Commercial use:** {'permitted' if rec.commercial_use else 'NOT PERMITTED'}")
            if rec.revenue_cap_usd:
                cap = rec.revenue_cap_usd / 1_000_000
                lines.append(
                    f"- **Revenue cap:** free commercial use below ${cap:.0f}M annual revenue; "
                    "an enterprise licence is required above it"
                )
            if rec.territory_exclusions:
                lines.append(f"- **Territory excluded:** {', '.join(rec.territory_exclusions)}")
            if rec.training_data:
                lines.append(f"- **Training data:** {rec.training_data}")
            lines.append(f"- **Assets from this model:** {count}")
            lines.append("")

        lines += ["## Assets", "", "| Cue | Kind | File | Engine | Seed | Length | Prompt |",
                  "|---|---|---|---|---|---|---|"]
        for r in self.records:
            prompt = r.prompt.replace("|", "/")
            if len(prompt) > 70:
                prompt = prompt[:67] + "..."
            lines.append(
                f"| {r.cue_id} | {r.kind} | `{r.file}` | {r.engine} | {r.seed} "
                f"| {r.duration:.2f}s | {prompt} |"
            )

        lines += ["", "---", "",
                  "_Generated by Saand Efectos. Licence terms were recorded at render time; "
                  "verify against the linked licence before relying on this for a "
                  "high-stakes release._", ""]
        return "\n".join(lines)
